- package.json
> Force specific version of ng2-bootstrap to fix build errors

- package.json
> Freeze angular-2-template-loader at specific version

- package.json
Reverts crdschurch/crds-connect#6
> Revert "Freeze angular-2-template-loader at specific version"

- package.json
- src/styles/application.scss
> Defect/Fix Build

- src/app/components/authentication/authentication.component.ts
- src/app/components/neighbors/neighbors.component.ts
- src/app/components/pin-details/pin-details.component.spec.ts
- src/app/components/pin-details/pin-details.component.ts
- src/app/route-resolvers/user-data-resolver.ts
- src/app/services/api.service.ts
- src/app/services/session.service.spec.ts
- src/app/services/session.service.ts
- src/app/services/store.service.ts
- src/app/services/user-location.service.ts
Reverts crdschurch/crds-connect#41
> Revert "DE2805 - Get ContactId from MP if we don't have it."

- package.json
> DEXXXX Lock crds-styles

- src/app/components/map/map.component.html
Create the map with the street view control turned off.
> us7224 - turn off the street view control with extreme malice.

- src/app/components/pin-details/pin-login-actions/pin-login-actions.html
Removed the signin/register link
> no sign in or register links

- src/app/directives/google-map-cluster.directive.ts
for fine tuning experimentation
> pull out the minimum cluster limit

- src/app/services/google-map.service.ts
- src/app/services/user-location.service.ts
- src/app/services/user-location.spec.ts
> Timeout in 15 seconds if user does not allow geoloc

- src/app/directives/google-map-cluster.directive.ts
Just setting an option on the MarkerClusterer
> place cluster marker at its “center”

- src/app/components/map-footer/map-footer.component.css
- src/app/components/search-bar/search-bar.component.css
- src/index.html
Some go to absolute, some get positioned using margins, some fill 100% x 100%. Various methods.
> Change formatting of fixed elements to not be

- src/app/components/register/register.component.spec.ts
Fix typo in test.
Corresponds with development branch of crds-styles.
> US7277 - Update markup for user authorization

- src/app/components/map/map.component.ts
- src/app/components/neighbors/neighbors.component.ts
- src/app/services/list-helper.service.spec.ts
just let doSearch do it’s work
> defect/de2963 don't show map until search completes

- src/app/components/pin-details/say-hi/say-hi.component.ts
- src/app/components/pin-details/say-hi/say-hi.html
- src/app/services/content.service.ts
TODO: Switch to crds-ng2-content-block
> Say hi is now a contentblock.

- package.json
- src/app/app.module.ts
Update crds-connect to consume new version of `crds-ng2-content-block`
> US7434 Content Blocks

- package.json
Lock crds-styles to latest version
> US7290 Dependencies

- src/app/components/map-content/map-content.component.ts
> How do I update the map in crds-connect to use Google Map Silver Theme https://mapstyle.withgoogle.com/ ?
I added the silver theme to the project.
Corresponds with the development branches of all repos.
> US6919 - Theme for Google Maps

- src/app/components/list-view/list-view.component.html
- src/app/components/list-view/list-view.component.ts
- src/app/models/group.ts
Merge this after the crds-angular branch
> US7251 - use participantCount

- src/app/components/search-local/search-local.component.html
> defect/de3085 - change button title

- src/app/components/map/map.component.ts
Implement protocol agnostic URLs
> DE3061 Pins on Map

- src/app/components/neighbors/neighbors.component.ts
null was the original start condition, but should have been -1
> proximity start condition

- src/app/components/search-local/search-local.component.html
- src/styles/application.scss
Refactor markup and add styles so the "Update results" button is positioned/styled in accordance to the approved design.
Reference: https://projects.invisionapp.com/share/VRAO3U5ST#/screens/221711952
----------
As a Connect user, I want to pan the map manually and be able to redo the search in the area that I've isolated on the map. 
> US7566 - Redo search button

- src/app/components/canvas-map-overlay/canvas-map-overlay.component.ts
- src/styles/application.scss
Adjusting canvas-map-overlay component height and adjust label positions.
Also, added stroke and adjusted coloring, and host/me font and offset.
> defect/de3018 - fix label positioning

- src/styles/application.scss
Add pointer cursor to each list item on the list view.
----------
Within Connect (finder-int.crossroards.net) on Chrome and also in Firefox - 
Go to the list view.
Move over any item in the list view.
The hover state does not work (I'm not "getting the finger").
> DE3114 - Add hover state to list view

- src/app/components/canvas-map-overlay/canvas-map-overlay.component.ts
> lost hash tag in merge

- src/app/layout/header/header.component.html
Add xlink attr to svg#use element
> DE3118 Back Buttons iOS

- src/app/components/pin-details/gathering/gathering.html
> fixed hode address

- src/styles/application.scss
Fix z-index on fuaxdal elements to resolve an issue in the `crds-connect` implementation within `crds-maestro`. See [DE3093](https://rally1.rallydev.com/#/41662702253d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F104357430988) for more information.
> DE3093 Add Me To Map

- src/app/components/search-local/search-local.component.html
Change the case of results to Results.
Corresponds with crds-styles/development.
----------
Change case on "Update results" button to read "Update Results"
> DE3171 - Change update results text

- src/app/components/getting-started/getting-started.component.html
- src/app/components/getting-started/getting-started.component.ts
Comment out profile image on getting started
> US7767 - Remove Getting Started Images

- src/app/components/pin-details/pin-details.html
- src/app/services/bland-page.service.ts
- src/styles/application.scss
Add a header above the edit pin form
> DE3175 - Edit Pin Header

- src/app/components/list-view/list-view.component.html
- src/app/components/pin-details/pin-details.html
Connect pin details page has text that goes out of the container. See attached image.
1. Navigate to int.crossroads.net/connect
2. Click a Person's pin
Problem: pin details has text running off the dark area of the screen
> DE3169 - Pin Details Container

- src/app/components/authentication/authentication.component.ts
- src/app/components/pin-details/person/person.component.ts
- src/app/components/register/register.component.ts
defect/de3167-scroll-to-top-of-page
> Fix scroll problems

- src/app/components/pin-details/participants-list/participant-card/participant-card.html
- src/app/components/pin-details/pin-header/pin-header.html
- src/styles/application.scss
Fix me label color on the pin details page
> DE3217 - Me Pin Color

- src/styles/application.scss
Change the color of the 'X' on fauxdals to white.
To get to the escapable fauxdals:
1. "Get started" -> "Add me to map"
2. "List" -> "What's a host?"
----------
Add Me to the Map "X" button color is loo light, it should be White
> DE3229 - Fauxdal 'X'

- src/app/components/list-entry/list-entry.component.html
Update building avatar in list view.
This isn't the greatest solution, but because it's temporary, I just threw an image up on S3 and then linked to it using the new profile picture method.
> US7793 - Updated Building Image

- src/app/components/map/map.component.ts
- src/app/services/session.service.ts
This is fixing a bug where a site can't be considered the current person.
The bulk of the work was simply switching out the icon on S3.
> US7623 - Add Building Icon To Map

- package.json
- src/app/app.module.ts
Update package.json for latest version of crds-ng2-content-block
> DEXXXX Lock crds-ng2-content-block

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.routing.ts
- src/app/components/add-me-to-map/add-me-to-map.component.spec.ts
- src/app/components/add-me-to-map/add-me-to-map.component.ts
- src/app/components/bland-page/bland-page.component.spec.ts
- src/app/components/bland-page/bland-page.component.ts
- src/styles/application.scss
Ensure fauxdal elements consume the entire viewport, toggle scrollbars appropriately when opened/closed.
> DE3220 Add Me To Map Overlay

- package.json
- src/app/components/add-me-to-map/add-me-to-map.component.html
- src/app/components/add-me-to-map/add-me-to-map.component.spec.ts
- src/app/components/add-me-to-map/add-me-to-map.component.ts
- src/app/components/pin-details/gathering/gathering.component.spec.ts
- src/app/components/pin-details/gathering/gathering.component.ts
- src/app/components/pin-details/gathering/gathering.html
- src/app/components/pin-details/person/person.component.ts
- src/app/services/base-service/cacheable.service.ts
- src/app/services/pin.service.ts
> fixed address, added lodash.  Im a super star.

- src/app/components/search-bar/search-bar.component.html
- src/styles/application.scss
Revert "Merge pull request #206 from crdschurch/feature/US7754-searchbar"
This reverts commit 5e898e261d068e4251683ea8f179edc879e1928d, reversing
changes made to 9571260947a2aacf9c1106830c33b82037d4c30c.
crdschurch/crds-styles#94
crdschurch/crds-connect#216
crdschurch/crds-styleguide#103
> DE3270 Revert Search Bar

- src/app/components/pin-details/say-hi/say-hi.component.ts
This feature branch removes the text-lowercase helper on the success and error message for the Say-Hi component.
> DE3231 - Incorrect Capitalization

- src/app/components/pin-details/gathering/gathering.html
> dont do that thing no mo

- package.json
Lock version to 0.4.0
crdschurch/crds-styleguide#106
crdschurch/crds-connect#225
crdschurch/crds-maestro#46
> US7883 CRDS Styles

- src/app/components/map-content/map-content.component.ts
> Fix bug that causes labels to be redrawn too frequently

- src/app/components/map-content/map-content.component.ts
- src/app/directives/google-map-cluster.directive.ts
- src/app/services/google-map.service.ts
> Add sites to clusters

- src/app/components/host-application/host-application.component.ts
- src/app/services/host-application-helper.service.ts
> Defect Not On Board - Fix for Phone Number on Signup to Host Story

- src/app/components/host-application/host-application.component.html
- src/app/components/host-application/host-application.component.spec.ts
- src/app/components/host-application/host-application.component.ts
> Add content blocks

- src/app/components/host-application/host-application.component.html
- src/app/components/host-application/host-application.component.ts
- src/styles/application.scss
https://invis.io/Y6A640O35#/215891553_02-03-04b-Finder-Connect-Results-Listed-Learnmore
faudal + form page
hide/show on home/not home address
This should require fairly little work. This is a 3 step process:
1. What's a host (content block & btns)
2. Host info form (content block, form fields, validation, btns)
3. Confirmation page (content block, btns) -- unknown if this pg will use the blandPageService?
Most of these elements should already exist no problem in crds-styles and these pages should use the fauxdal template which is largely good to go. Just need to assemble all elements and clean up as needed.
> US7922 - Host Sign Up

- package.json
Update crds-ng2-content-block to latest version
> DE3347 XHR Race Conditions

- src/app/components/list-view/list-view.component.html
- src/app/components/pin-details/gathering/edit/gathering-edit.component.html
- src/app/components/pin-details/gathering/gathering.html
- src/app/components/pin-details/person/edit/person-edit.component.html
- src/app/components/pin-details/person/person.html
- src/styles/components/_media-objects.scss
This adjusts the markup for `gathering/:id/edit` and `person/:id/edit` so that it uses the dark theme and looks oh so pretty.
---
Hosts should be able to edit their personal details for gatherings
Looks like a component to support this already exists in the application, page needs to be styled
> US7923 - Edit Host Details

- src/app/components/address-form/address-form.component.html
- src/app/components/host-application/host-application.component.html
> DE3391 Tab Order

- src/app/app.component.ts
Reposition viewport when the route changes
> DE3378 Scroll To

- src/app/components/host-application/host-application.component.html
Change input type on phone number field in host signup form.
----------
It looks like the field type is set to text instead of "tel". It should preferably also be formatted like a phone number (###-###-####). See profile mobile phone field.
> DE3409 - Phone number input

- src/app/components/pin-details/person/edit/person-edit.component.html
- src/app/components/pin-details/person/edit/person-edit.component.ts
Add "me" label to the edit pages on pin details.
----------
Clicked on my pin as a person.
See the details page.
The label at the top of the details page correctly shows "Me".
Click on edit to change the address.
The label now shows "Host" (incorrect...should still say "Me").
> DE3410 - Label on edit page

- package.json
Update crds-styles to latest version
> US8050 Publish NPM Package

- src/styles/application.scss
Add smooth scrolling for mobile devices
> DE3371 - Fauxdal Height

- src/app/components/host-application/host-application.component.html
Add close button to upper right corner of fauxdal. Has same behaviour as cancel button at bottom of the page. Should look like Add me to Map page.
> DE3422 - Add 'X' to host signup page

- src/app/components/list-entry/list-entry.component.html
DE3433
This function was not yet complete so I commented out the line.
> Commented out joined by line.

- src/app/services/bland-page.service.ts
You ended a sentence in a preposition! You monster!
> DE3441 - Button copy update

- src/app/components/add-me-to-map/add-me-to-map.component.html
- src/app/components/pin-details/gathering/edit/gathering-edit.component.html
- src/app/components/pin-details/person/edit/person-edit.component.html
Per feedback from Brian, buttons affiliated with forms should be left-aligned, inline and the cancel button should look consistent across the site. 
Changed the button layouts on the Add Me to Map page, `/add-me-to-map`, `/gathering/*/edit`, `/person/*/edit`, and `/whats-a-host`.
> DE3417 - Button layout host edit

- src/app/components/getting-started/getting-started.component.html
relabel "sign up" on host form to "Sign up to host"
> US8098 - Change btn text on host signup page

- src/app/services/host-application-helper.service.ts
Minor fix for phone saving issue.
> Fix phone number

- src/app/shared/constants.ts
> US8199 - Add state lines

- src/app/components/pin-details/person/remove-person-pin/remove-person-pin.component.html
Make remove me from map page look like other fauxdals. You can get to this page from _your_ pin details, by clicking the "remove me from the map link" below the edit button.
---
Given a Connect user
When I remove myself from the map
Then I should see a success screen that utilizes the fauxdal and includes approved design/markup for fauxdal 
---
> US8398 - Remove Map Fauxdal

- src/app/components/map-footer/map-footer.component.html
- src/app/components/map-footer/map-footer.component.spec.ts
- src/app/components/map-footer/map-footer.component.ts
- src/app/components/neighbors/neighbors.component.html
- src/app/components/neighbors/neighbors.component.ts
- src/app/components/search-bar/search-bar.component.css
- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.ts
- src/app/services/state.service.ts
Reverts crdschurch/crds-connect#369
> Revert "Feature/us7911 get out of my stuff view"

- src/app/components/map-footer/map-footer.component.html
- src/app/components/map-footer/map-footer.component.spec.ts
- src/app/components/map-footer/map-footer.component.ts
- src/app/components/neighbors/neighbors.component.html
- src/app/components/neighbors/neighbors.component.ts
- src/app/components/search-bar/search-bar.component.css
- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.ts
- src/app/services/state.service.ts
> fix thingiesZ

- src/app/components/neighbors/neighbors.component.ts
- src/app/components/search-bar/search-bar.component.ts
Removed redundant code from onInit -  moved everything to onChanges.
> Save previous search on successful search submission

- src/app/services/login-redirect.service.ts
I really don't like this solution but it's like the only thing we can do when maestro puts a trailing /
> Handle /?resolve=true

- src/app/components/add-me-to-map/add-me-to-map.component.html
- src/app/components/bland-page/bland-page.html
- src/app/components/getting-started/getting-started.component.html
- src/app/components/host-application/host-application.component.html
- src/app/components/list-footer/list-footer.component.html
- src/app/components/list-view/list-view.component.html
- src/app/components/no-results/no-results.component.html
- src/app/components/pin-details/gathering/edit/gathering-edit.component.html
- src/app/components/pin-details/gathering/gathering-requests/gathering-requests.html
- src/app/components/pin-details/gathering/gathering.html
- src/app/components/pin-details/gathering/invite-someone/invite-someone.html
- src/app/components/pin-details/person/edit/person-edit.component.html
- src/app/components/pin-details/person/person.html
- src/app/components/pin-details/person/remove-person-pin/remove-person-pin.component.html
- src/app/components/pin-details/say-hi/say-hi.html
- src/app/components/stuff-not-found/stuff-not-found.html
- src/index.html
Given a developer viewing the DDK
When I view utility classes
Then i should see the .btn-block-mobile selector with a description of what it will do to help me make awesome buttons. 
Given a user viewing /connect
When I view a CTA throughout the application on mobile
Then it should be displayed 100% wide, block-level on my tiny screen
Given a user viewing /connect
When I view a CTA throughout the application on desktop
Then I should see inline-block elements that do not fill up 100% of my screen width. 
---
Corresponds with:
- crdschurch/crds-styles#142
- crdschurch/crds-styleguide#166
- crdschurch/crds-maestro#151
> US8429 - Block Level Buttons

- src/app/components/search-bar/search-bar.component.html
Add close icon to searchbar markup.
Corresponds with crdschurch/crds-styles#145 and crdschurch/crds-styleguide#168
> US8745 - Add close icon

- package.json
> US8844 - Publish NPM Package

- src/app/components/add-me-to-map/add-me-to-map.component.html
- src/app/components/add-me-to-map/add-me-to-map.component.spec.ts
- src/app/components/add-me-to-map/add-me-to-map.component.ts
Change validation to allow submit button to be clicked regardless of data entered.
---
Update form on Add Me To Map such that you can submit before data is entered
> US7921 - Add me to map validation

- package.json
- src/app/components/search-bar/search-bar.component.html
Given a Connect user
when I use the search on the map/list of Connect
Then that input field should use the input type "search" so that the keyword can persist and has a clear button
> US8009 - Mobile Search Keyboard

- package.json
> US8992 - Publish NPM Package

- src/app/components/pin-details/gathering/gathering.html
> US9047: Hide contact group leader button until it is brought back

- src/app/components/create-group/create-group-data.service.spec.ts
- src/app/components/create-group/create-group-data.service.ts
- src/app/components/create-group/page-1/create-group-page-1.component.html
- src/app/components/create-group/page-1/create-group-page-1.component.spec.ts
- src/app/components/create-group/page-1/create-group-page-1.component.ts
- src/app/components/create-group/page-2/create-group-page-2.component.html
- src/app/components/filters/age-groups/age-groups.component.spec.ts
- src/app/models/attribute.ts
- src/app/models/group.ts
- src/app/shared/constants.ts
-Save categories to model properly for entire flow submission
-Add missing unit tests that I forgot to write.
> -Fix button alignment

- src/app/components/filters/filters.component.spec.ts
- src/app/components/filters/filters.component.ts
- src/app/components/neighbors/neighbors.component.spec.ts
- src/app/components/neighbors/neighbors.component.ts
- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.ts
- src/app/models/search-options.ts
- src/app/services/participant.service.spec.ts
- src/app/services/pin.service.spec.ts
- src/app/services/pin.service.ts
- src/app/services/state.service.ts
~~DO NOT MERGE~~ We can merge once everyone takes a look
> re-implements cache in pinDetailsService, also fixes some logic errors

- src/app/components/pin-details/gathering/add-someone/add-someone.html
- src/app/components/pin-details/gathering/gathering.html
- src/app/components/pin-details/gathering/invite-someone/invite-someone.html
- src/app/components/pin-details/gathering/participant-card/participant-card.html
- src/app/components/pin-details/person/person.html
- src/app/components/pin-details/say-hi/say-hi.html
- src/styles/pages/_pin-details.scss
Update the styles and markup for the person and gathering details pages to match the updated design.
---
Update Finder UI with design updates from Rob (https://invis.io/68BRD8RXB#/234261460_04M-01a-Groups-Detail) 
Revising black bkg, font colors, badge colors, btn colors. 
> US9143 - Finder facelift

- package.json
> US9171 NPM Package

- src/app/components/pin-details/gathering/edit/gathering-edit.component.html
- src/app/components/pin-details/person/edit/person-edit.component.html
- src/app/components/pin-details/say-hi/say-hi.html
Change out the black backgrounds on the gathering/person edit details pages to match updated design.
No corresponding PRs
> DE3951 - Black bg

- src/app/components/pin-details/gathering/gathering.html
> Bring back contact group leader

- src/app/components/pin-details/person/remove-person-pin/remove-person-pin.component.ts
Previously determineStateToReturnTo looked at Map vs. List view;
now it looks at My Stuff vs World view
> Bug fix: determineStateToReturnTo now looks at My Stuff vs World view

- src/app/components/host-application/host-application.component.html
added id to submit button on connect sign up to host application
> added id for sign up to host submit btn

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
implementing astronomer in angulartics
> angulartics configured to report to astronomer

- package.json
- src/app/components/create-group/page-2/create-group-page-2.component.html
Adjust border radius on button.
Corresponds with crdschurch/crds-styles#174 and crdschurch/crds-maestro#203
> DE3959 - Timepicker styling

- src/app/components/contact-leader/contact-leader.component.ts
Touch all fields on form submit so that even pristine, invalid fields get validation styles.
See also crdschurch/crds-styles#176
> DE3971 Validation Styles

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/email-participants/email-participants.component.html
Given a designer/developer
When I need to implement a single button drop down
Then I should find styles for this in the DDK
Given a Crds Groups Leader
When I want to email all my participants
Then I should see a single button drop down wherein I can choose to email my participants or copy their email addresses (this story only governs the styles of that drop down, not the functionality of the drop down)
Given a Crds Connect Host
When I want to email all my participants
Then I should see a single button drop down wherein I can choose to email my participants or copy their email addresses (this story only governs the styles of that drop down, not the functionality of the drop down)
---
Corresponds to crdschurch/crds-styleguide#191 and crdschurch/crds-styles#175.
> US9172 - Single Btn Dropdown

- src/styles/components/_searchbar.scss
Reverts crdschurch/crds-connect#527
> Revert "The filters box now acts as a dropdown that overlaps the map or list"

- src/app/components/filters/filters.component.html
- src/app/components/filters/meeting-day/meeting-day.component.html
- src/app/components/filters/meeting-frequency/meeting-frequency.component.html
- src/app/components/filters/meeting-time/meeting-time.component.html
Update markup on frequency filter so subheaders look good.
Corresponds with crdschurch/crds-styles#181
> DE4025 - Filter fonts

- src/styles/pages/_pin-details.scss
Modify font colors to match design.
---
Fonts on the attributes withinhttps://invis.io/68BRD8RXB#/234261460_04M-01a-Groups-Detail Group Detail do not match design.
> DE4006 - Group detail fonts

- src/app/components/contact-leader/contact-leader.component.html
Refactor markup for the form fields and add font style classes to all 3 CMSs.
> US9306 - Contact fauxdal

- src/app/components/list-entry/list-entry.component.html
- src/app/components/list-entry/list-entry.component.ts
- src/app/shared/constants.ts
> DE4042: Fix Proximity

- src/app/app.component.ts
- src/app/components/search-bar/search-bar.component.html
- src/index.html
- src/styles/application.scss
Given a Groups user
When I view the Finder Group Tool
Then I should see a search bar that matches the approved design
---
Note there is some "graceful" degradation in IE 10/11 with the size of the button. I'd rather create a defect to address that specifically, but if you want that fixed here, can do.
---
Corresponds to crdschurch/crds-styleguide#193 and crdschurch/crds-styles#182.
> US9300 - Search Bar Fixes

- src/app/components/search-bar/search-bar.component.html
Exclude filter icon from /connect
> DE4031 Filter Icon

- package.json
> US9403 crds-styles

- src/app/components/pin-details/gathering/add-someone/add-someone.component.ts
https://rally1.rallydev.com/#/66097202244d/detail/defect/136116265044
> Page now scrolls to top after adding a new member to a group

- src/app/components/pin-details/gathering/participant-remove/participant-remove.component.html
Center justify buttons when removing self from group
> DE4063 Remove Participant Styles

- package.json
> Update the styles version to point to development branch.

- src/app/services/app-settings.service.ts
connect redirect no goes to add me to the map
> added connect redirect

- src/app/components/create-group/preview/create-group-preview.component.html
- src/app/components/pin-details/gathering/gathering.component.ts
- src/styles/pages/_group-preview.scss
- src/styles/pages/_modules.scss
> DE4075 Group Form Preview

- src/app/components/neighbors/neighbors.component.ts
Added markup to a bland style page so it matches other bland pages.
Good luck recreating! I got there by signing in and clicking the My Groups button in the header. This works some of the time... 
Here's how the page looks on my screen:
No corresponding PRs
> DE4082 - oops

- src/app/components/create-group/page-1/create-group-page-1.component.html
- src/app/components/create-group/page-1/create-group-page-1.component.ts
Add back button to create-group page #1
> DE4079 Start Group Back Button

- src/app/components/create-group/create-group-data.service.ts
- src/app/components/create-group/page-1/create-group-page-1.component.ts
- src/app/components/pin-details/gathering/gathering.component.spec.ts
- src/app/components/pin-details/gathering/gathering.component.ts
> Fix group data not populating.

- src/app/components/create-group/page-2/create-group-page-2.component.ts
- src/app/shared/constants.ts
> Fix time issue

- src/app/components/create-group/page-1/create-group-page-1.component.html
- src/app/components/create-group/page-1/create-group-page-1.component.spec.ts
- src/app/components/create-group/page-1/create-group-page-1.component.ts
This commit reverts the changes made in
7e05d6a2556358f6baa08a3f2883934c490dea96
> DE4079 Revert Start Group Back Button

- src/app/components/create-group/create-group-footer/create-group-footer.component.html
Change
"Leave form?
Select Yes to proceed and lose current changes. Select No to abort?"
to 
"Are you sure you want to cancel?
By canceling, all changes will be lost. Select yes to proceed or no to continue working on your group."
> DE4118 - Change message

- src/app/components/create-group/page-5/create-group-page-5.component.html
- src/app/components/create-group/page-5/create-group-page-5.component.spec.ts
- src/app/components/create-group/page-5/create-group-page-5.component.ts
https://rally1.rallydev.com/#/66097202244d/detail/defect/143196375860
> Errors in step 5 of create group now display correctly

- src/app/components/try-group/try-group-request-confirmation/try-group-request-confirmation.component.ts
https://rally1.rallydev.com/#/66097202244d/detail/defect/144920924428
> Submitting a request to try a group now displays a spinner

- src/app/components/create-group/page-2/create-group-page-2.component.ts
> Fix meeting frequency

- src/app/components/create-group/page-4/create-group-page-4.component.html
Fix this:
---
crdschurch/crds-styles#200
crdschurch/crds-styleguide#210
> DE4124 - Button Text Overflow

- package.json
Update crds-styles to latest version
> US9573 Publish NPM Package

- src/app/services/google-map.service.spec.ts
- src/app/services/google-map.service.ts
https://rally1.rallydev.com/#/66097202244d/detail/defect/146934640440
> No longer zooms out to whole world when results have online groups

- src/app/components/pin-details/gathering/gathering.html
- src/app/components/pin-details/gathering/social-media/social-media.component.html
- src/app/components/pin-details/gathering/social-media/social-media.component.ts
Reverts crdschurch/crds-connect#645
> Revert "Defect/de4164 post group to fb"

- src/app/components/pin-details/gathering/social-media/social-media.component.html
- src/styles/pages/_pin-details.scss
Fix clickable area on pin details icons
> DE4166 - Clickable Icon Area

- src/app/components/neighbors/neighbors.component.ts
> US9460-my-groups

- src/app/components/pin-details/gathering/participant-remove/participant-remove.component.html
Cleanup the markup around the remove participant fauxdal.
> US9731 - Cleanup remove participant fauxdal

- src/app/components/create-group/create-group-data.service.ts
- src/app/components/create-group/page-1/create-group-page-1.component.spec.ts
- src/app/components/create-group/page-1/create-group-page-1.component.ts
- src/app/components/create-group/page-3/create-group-page-3.component.ts
> DE4220: Fix category selection bypassing max cat limit

- src/app/components/pin-details/gathering/gathering.html
> Remove the link to end group from front end

- src/app/components/create-group/page-6/create-group-page-6.component.html
There were a couple more error fields that needed auto-ids.
> More automation ids added.

- src/app/components/create-group/preview/create-group-preview.component.spec.ts
- src/app/components/create-group/preview/create-group-preview.component.ts
> HOTFIX lololol

- src/app/components/pin-details/gathering/participant-remove/participant-remove.component.ts
Remove one of the scrollbars from fauxdal.
Not removing both because this fauxdal has 2 versions: one with verbose content and another with shorter text. 
No corresponding PR
> DE4241 - Remove self fauxdal

- src/app/services/search.service.spec.ts
- src/app/services/search.service.ts
This PR should fix the following console error in connect:
> Call the function not check if the function exists

- src/app/app.module.ts
- src/app/app.toast.options.ts
- src/app/components/contact-leader/contact-leader.component.spec.ts
- src/app/components/contact-leader/contact-leader.component.ts
- src/app/components/pin-details/gathering/participant-details/participant-details.component.ts
I also pulled out the configuration class into its own file.
> Toast life 5s

- src/app/components/create-group/page-4/create-group-page-4.component.html
Change alert from danger to warning when selecting an age group under 18.
No related PRs.
> DE4308 - Change alert type

- package-lock.json
- src/app/app.component.ts
- src/app/components/bland-page/bland-page.component.ts
Fix overflow upon leaving getting started page.
Steps to reproduce:
- go to /connect
- click Get started
- click whats a host button
- click cancel
- Can't scroll
> DE4323 - Scroll Lock

- src/app/components/create-group/create-group-data.service.spec.ts
- src/app/components/create-group/create-group-data.service.ts
Also write missing unit tests forever.
> set contact id from groupBeingEdited

- src/app/components/pin-details/gathering/gathering.component.ts
- src/app/components/pin-details/gathering/gathering.html
https://rally1.rallydev.com/#/66097202244d/detail/defect/151730547492
> Re-enabled End Group for all group leaders

- .angular-cli.json
- src/environments/environment.ample.ts
Update variables and build commands so we can access the app.
> US10035 - Ample environment variables

- src/app/components/search-bar/search-bar.component.html
- src/environments/environment.ts
- src/styles/components/_searchbar.scss
Make the list toggle visible on mobile
> (1/7) DE4386 - List Toggle Visibility

- src/app/components/search-bar/search-bar.component.html
- src/environments/environment.ts
- src/styles/components/_searchbar.scss
(Built atop #718.)
Toggle X visibility appropriately.
> (2/7) DE4395 - Conditional X

- src/app/components/search-bar/search-bar.component.html
- src/environments/environment.ts
- src/styles/components/_searchbar.scss
Depends on #718 and #720 
Adds divider between inputs on desktop
> (3/7) DE4391 - Desktop Divider

- src/app/components/pin-details/person/remove-person-pin/remove-person-pin.component.ts
Remove the double scrolls from remove me from map fauxdal.
No corresponding PRs
> DE4326 - Remove me fauxdal

- src/app/components/search-bar/search-bar.component.ts
Build event path manually to fix iOS.
> DE4392 - Click To Collapse

- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.ts
- src/styles/components/_searchbar.scss
Show X on mobile after searching a keyword.
> DE4416 - Persistent X

- package.json
Connect this app to development styles.
Corresponds to crdschurch/crds-styles#224
> DE4421 - Filter accordion style

- src/app/components/search-bar/location-bar/location-bar.component.html
Update placeholder text in location-bar component.
> US10085 Placeholder Text

- src/app/components/pin-details/say-hi/say-hi.html
Update the 'say hi' button in /connect to cyan.
> DE4441 - Update hi button

- package.json
so local environment works correctly still in maestro
> use build-optimizer in local build
