- src/app/components/register/register.component.html
Fixing broken link on the email field. If registering an account with an email already in use, the validation message should contain a link to sign-in.
Corresponds with the development branch of crds-styles.
> US7277 - Update markup for user authentication

- src/app/components/search-bar/search-bar.component.html
I fixed the attribute linking to the search SVG. 
Corresponds with crds-styles/development and crdschurch/crds-styleguide#87
----------
the magnifying glass icon in the search submit button does not show in safari on ios and mac 
> DE3028 - Search icon missing in Safari/iOS

- src/app/directives/google-map-cluster.directive.ts
Changing the size of the cluster marker centers the icon text.
Corresponds with the development branches of crds-styles/development
----------
the number inside the cluster icon is not centered in the icon
> DE3051 - Center cluster labels on icons

- src/app/components/neighbors/neighbors.component.ts
Sort the pins by proximity (asc) and then firstName (asc), lastName (asc), and pinType (des), then uniq them by proximity, firstName and lastName. This gets rid of person pin types with the same proximity and name as host pins.
> US7511 Remove ‘duplicate’ pins

- src/styles/application.scss
Refactor the centering class used on the searchbar area. The flexbox properties got overwritten in a merge, which is why the horizontal alignment was off.
-------------
Search Bar and list/Map Toggle are misaligned vertically
> DE3113 - Align the buttons and searchbar

- src/app/components/map-content/map-content.component.ts
- src/app/components/map-footer/map-footer.component.html
- src/app/components/neighbors/neighbors.component.ts
- src/styles/application.scss
From @zarahzachz:
> what taylor, brian and becky netted on for this was that:
>
> 1. we need to disable the scroll-zoom so the user can scroll on the page successfully (done)
> 2. change the height of the map to a fixed px-based height and it's ok if the content scrolls past the bottom of the screen (for mobile) or there's white space (desktop) (kinda done?)
> 3. footer buttons should be reconfigured to be positioned at the top of the map so they aren't cut off on small screens
> 
> i'd suggest adding some media queries on the height so it's not so jarring on different devices
> 
> and taylor recommended repositioning all of the map buttons (redo search, my pin and getting started) to sit vertically atop each other on the top-right side of the screen
> US7699 - Refactor Map Size

- src/app/services/google-map.service.ts
But not further than level 3, since the map setup limits zoom to be between 3 and 20.
> zoom until you see 10 pins

- src/app/components/address-form/address-form.component.html
- src/styles/application.scss
Add btn link style for a cancel button to add-me-to-map. Should redirect to the previous page (/getting-started) and be positioned vertical/center.
Access by going to Get started -> Add me to map.
----------
When I navigate to the Add me to the map page there is no cancel button, but there should be.
> DE3228 - Add cancel button

- src/styles/application.scss
Increase clickable area around 'X' on fauxdals.
Peter pointed that on Edge 14, the right side of the icon didn't have a hover state (but it was the only browser with this problem). Increasing the clickable area fixes this problem and helps people with fat hands navigate.
> DE3229 - Fauxdal 'X'

- src/app/components/map-content/map-content.component.ts
Remove the fullscreen map button functionality - this feature is not supported across all mobile devices. 
in an Android browser, there is a Full Screen map toggle underneath the Get Started Button on /connect
> DE3307 - Disable fullscreen map btn

- src/styles/application.scss
Temporary fix to increase the contrast of active/non-active buttons.
"My stuff" button should have more obvious active state. Test by adding/removing `active` to this button.
----------
The active state should be a more obvious different color than the inactive state.
> DE3264 - Active buttons

- package.json
- src/styles/application.scss
Add local style to fix shadow on searchbar input field. Only visible in iOS.
*This style already exists in `crds-styles/development` but because we've locked the versions, `crds-connect` can't access this updated style. This style is added as a fix until it can access the latest from `crds-styles/development`*
> DE3299 - Input shadow on iOS

- src/app/components/map-footer/map-footer.component.ts
Add the class of active to the My stuff button once the button is clicked, regardless if the user is logged in or not.
----------
While not being logged in, Click "My Stuff" > Sign In as a user with Stuff on the Map => Goes back to the map and the My Stuff button is not in the active state. 
This Should be in an active state at this point.
It seems to be working as expected in other scenarios.
> DE3328 - Fix my stuff button

- src/styles/application.scss
Toggle button look/behaviour is still being decided on. Being pulled out of DDK/`crds-styles` and moved into `crds-connect` as a connect-specific style until further defined.
Corresponds with:
crdschurch/crds-styles#101
crdschurch/crds-styleguide#111
> US7849 - Toggle btn ddk

- src/styles/application.scss
In my hubris, I thought I could fix something even The Mighty Google Maps could not fix.
Removing the increased z-index fix on the map overlay.
> US7962 - Roll back the map overlay fix for iOS

- src/app/components/pin-details/gathering/gathering-requests/gathering-requests.component.spec.ts
- src/app/components/pin-details/gathering/gathering-requests/gathering-requests.component.ts
- src/app/components/pin-details/gathering/invite-someone/invite-someone.component.spec.ts
- src/app/components/pin-details/gathering/invite-someone/invite-someone.component.ts
- src/app/components/pin-details/say-hi/say-hi.component.ts
- src/app/services/pin.service.ts
As a Connect user or host, I should see confirmation screens that match the approved design when I transact with other users.
---
All I did here was look for instances of `BlandPageType.Text` and fixed the markup so it would appear. In _many_ of these cases, there's really no easy way to make the confirmation page appear. And that's problematic for passing this on to QA, so I'm open to suggestions. (Perhaps this should sit here until all of the confirmation screens are working properly?)
> US7375 - Clean Up Confirmation Screens

- package.json
- src/app/components/host-application/host-application.component.ts
Due to the number of instances within `crds-connect` relying on an old implementation of the `getContent()` method in the `crds-ng2-content-block` package, this PR reverts that dependency to `v1.0.2`. 
---
Revert "get content as observable"
This reverts commit 65fc3980bb79fd7164712257ddaa1cfeb82a5c75.
> DEXXXX Revert CRDS NG2 Content Block

- src/app/components/pin-details/pin-details.html
Remove conflicting class to remove padding.
------
The dark background on the pin details (individual & host) should but full width on mobile.
https://www.dropbox.com/s/o17556l8xome1gc/Screenshot%202017-04-28%2014.42.56.png?dl=0
> DE3414 - Pin details mobile bg

- src/app/components/host-application/host-application.component.html
Move buttons to left-aligned, inline with each other. Change the default button to the gray outline button.
----------
On the host edit screen, the buttons are centered and stacked vertically. They should be inline and aligned to the left (or right), like other forms buttons on the site.
https://projects.invisionapp.com/d/main#/console/9595176/209360074/preview
I'm also not sure the "Cancel" button should be a btn-link, I'd lean towards an outline button here but I'll let Rob make that call. Regardless, I'd like us to pick a "Cancel" button pattern and make that consistent everywhere.
> DE3417 - Button layout on host edit page

- src/app/components/host-application/host-application.component.html
On the host signup page, the phone number field reads "Contact Number" which is confusing. We're asking the user for a phone number so it should read "Phone Number". Don't forget to correct the error message too.
> DE3421 - Fix phone number text on host signup page.

- src/app/components/list-entry/list-entry.component.html
All labels for "ME" should have ".label-warning" (yellow background) applied.
> DE3462 - Fix label color

- src/app/components/pin-details/gathering/invite-someone/invite-someone.html
Remove tabindex.
Test by signing in as a Gathering Host Cool Person Supreme, and going to the Gathering pin details page. Enter info in the "Invite Someone" section and tab around. The submit button should be included in the appropriate flow.
---
When completing the invite form on the host details page, tabbing skips the submit button.
http://quick.as/nmV1ID7wo
> DE3411 - Invite form btn skips

- src/app/components/pin-details/pin-details.html
Fix pin details container for maestro.
This was only an issue in Maestro, but because it affects code in Connect, should be tested locally in both Maestro and Connect.
---
> DE3527 - Pin Details Container Too Wide

- src/app/components/list-view/list-view.component.html
Remove `.container-fluid` from the layout because it breaks everything. (We should probably review how we're using this class in the future because it feels... inappropriate?)
Test /connect and maestro/connect locally.
---
Sections with gray backgrounds on the List View of /connect are broken (shifted up and to the left of intended layout).
> DE3526 - List view layout jacked up

- src/app/components/list-view/list-view.component.html
- src/app/components/pin-details/pin-details.html
Remove `.container-fluid` from gathering pin details page so the black section doesn't expand past the rest of the layout.
Test both maestro and normal /connect. **Keep yer eyes peeled - this fix *may* have introduced regressions (though I didn't find any).**
---
Navigate to a gathering  with participants. The black section at the top extends past the white sections beneath (by about 15px left and right).
> DE3541 - Gathering pin details page layout

- src/app/components/pin-details/gathering/invite-someone/invite-someone.component.ts
- src/app/components/pin-details/gathering/invite-someone/invite-someone.html
Update the submit button on the "send invite" form so it's never disabled and validates form fields after submission.
---
When I am looking at my Gathering (Logged in as a Host, viewing my Gathering Pin Details) the "Send Invite" button should always be clickable (mobile friendly) and show the appropriate error functionality
> DE3386 - Send invite button

- src/app/components/pin-details/person/remove-person-pin/remove-person-pin.component.ts
Add class of .fauxdal-open to the body to prevent duplicate scrollbar from popping up.
No corresponding PR.
**Check out fauxdals locally in Maestro to account for the length of the footer (this is what caused the duplicate scrollbar)**
---
Peter re-opened this defect. Spotted a duplicate scrollbar on the "Remove me from map" fauxdal when using Chrome on PC. Defect not visible on other fauxdals in the application.
> DE3528 - Remove me from map fauxdal

- src/styles/pages/_pin-details.scss
Change the height of person/gathering pin details page from explicitly stated height to a min-height. This allows the content to increase the size of the container rather than causing additional content to overflow into the footer.
No other related PRs out there.
> DE3668 - Pin details content overflows

- src/app/components/getting-started/getting-started.component.html
- src/app/components/list-footer/list-footer.component.html
- src/app/components/no-results/no-results.component.html
- src/app/components/pin-details/person/remove-person-pin/remove-person-pin.component.html
Fix issue with mobile block buttons not taking up the appropriate space on the page. In response to:
> on the getting started page on iOS, the Host buttons bleeds into the footer
> DE3747 - Getting Started Buttons

- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.ts
when clicking the X button to clear the search bar, the keyboard is dismissed
Note: this is relevant to Finder, the search input at the top had a clear icon added to them
> DE3754 - X Keyboard

- src/app/components/list-entry/list-entry.component.html
- src/styles/components/_media-objects.scss
Style the group attributes to the design.
---
The list view of the Finder tool needs to be updated to include styles for the additional groups attributes that will be added. List view on Connect currently looks like this:
For Groups, need to add the following:
Meeting day/time
Group category
Group detail
Group type
Group leader
Will look more like this: https://invis.io/68BRD8RXB#/234261457_02M-01a-Groups-List
> US8554 - List view group attributes

- src/app/components/pin-details/gathering/participant-details/participant-details.component.ts
- src/app/components/pin-details/gathering/participant-details/participant-details.spec.ts
Changed participant-details.component to do nothing when assigning a
user to a role they already are.  Added testing for the component's
saveChanges() method.
> Growl no longer appears when reassigning a full role

- src/app/components/create-group/create-group-summary/create-group-summary.component.html
- src/app/components/create-group/page-1/create-group-page-1.component.html
- src/app/components/create-group/page-2/create-group-page-2.component.html
- src/app/components/create-group/page-3/create-group-page-3.component.html
- src/app/components/create-group/page-4/create-group-page-4.component.html
- src/app/components/create-group/page-5/create-group-page-5.component.html
Given a user starting a group by filling out the "start a group" form
When defining the 'group category'
Then I should see fields to select & define attributes associated with one or more categories (Interest, Neighborhood, Spiritual Growth, Life Stages, Healing)
Given a user starting a group by filling out the "start a group" form
When defining the 'meeting time'
Then I should see fields to specify a specific day, time (via time picker) and meeting frequency OR specify that my group's meeting time is 'Flexible / TBD'
Given a user starting a group by filling out the "start a group" form
When defining the 'meeting location'
Then I should see fields to specify 'In Person' (address, city, state, zip & kids) OR 'Online' (TBD)
Given a user starting a group by filling out the "start a group" …
> US8620 - Start Group Markup

- src/styles/pages/_pin-details.scss
Fix the form label text color to work with the new blue background.
No corresponding PRs
---
Steps to reproduce
-go to /connect
-click My Stuff
-Log in (tester21@gmail.com, password=password)
-click into the Gathering
Actual results = "Meetings At" text color is wrong
Expected result = Color is right ;-)
> DE3955 - Text color

- src/app/components/create-group/page-1/create-group-page-1.component.html
- src/app/components/create-group/page-2/create-group-page-2.component.html
- src/app/components/create-group/page-3/create-group-page-3.component.html
Given a designer/developer 
When implementing a btn form group on a Crds application
Then I should find implementation details for the updated btn group in the DDK with the vertical rule for indented/child options rather than the caret
Given a crds.net/groups user
When starting a group
Then I should see the updated btn form group implemented within any selections that have nested child options 
---
Corresponds to crdschurch/crds-styleguide#189 and crdschurch/crds-styles#173.
> US9159 - Btn Indent Styles

- src/app/components/pin-details/gathering/gathering-requests/gathering-requests.html
Change participant request buttons from full-width on mobile to side-by-side.
---
Steps to reproduce
One mobile screen
-go to /connect
-click My Stuff
-log in (tester21@gmail.com, password=password)
-click list toggle
-Click into host
Actual result = buttons are wide and stacked on top of each other
Expect result = buttons should be side by side
> DE3968 - Accept/deny buttons

- src/app/components/address-form/address-form.component.html
https://rally1.rallydev.com/#/66097202244d/detail/defect/140576807632
> Address Form's Zip Code field now accepts long format (i.e. #####-####)

- src/app/components/neighbors/neighbors.component.html
Hide map/list if search filter is visible.
No other PRs.
---
Finder Groups filter, when expanded, should cover entire view behind it. Currently the layer below is visible at the bottom of the map. 
> DE4000 - Filter takeover

- src/app/components/pin-details/gathering/gathering.html
Add link icon to pin details and make visible at all times.
Modify the group detail view such that the social icons appear outside of the expanded description field. User should not have to expand description to access the social icons to share the group. Defer to Rob for positioning as needed. 
Also we need to add a link icon so the user can copy the direct URL to the group.
Corresponds with crdschurch/crds-styles#180
Corresponds with crdschurch/crds-styleguide#192
> US9342 - Social icons

- src/app/components/contact-leader/contact-leader.component.ts
Remove the scrollbar from the contact leader form. This fixes the margin spacing to the right of the content so it looks good on mobile.
This has no corresponding PRs.
> US9306 - Contact fauxdal

- src/app/components/getting-started/getting-started.component.html
- src/styles/application.scss
Given a CMS user
When authoring content in the CMS that should live within the Connect application containers
Then I should be able to lead with an H tag without creating a gap at the top of the connect container. 
---
See more about the tabs here: https://stackoverflow.com/a/2890369/2241124
---
No other corresponding PRs.
> US9346 - Container Padding Top

- src/app/components/create-group/page-2/create-group-page-2.component.ts
Add style override for button text overflow.
---
**Modify this short term such that the labels are cleaned up and don't flow off the btn on smaller device widths. The longer term solution will be governed by a story that incorporates Rob's adjusted design and approach for how to utilize these buttons.
-BB
Back next buttons do not match design, also the Right-text on the option button is cut off (see attached screenshot for both issues)
> DE4044 - Create group btns text explosion

- src/styles/components/_header.scss
Note– since this is a very specific implementation of `.btn-link.active` _and_ since the button styles in the DDK will be updated in the near future, I opted to apply this change locally to this one instance after consulting w/ @amplerob. 
Let me know if you have any concerns.
> DE4078 My Groups Active State

- src/app/components/pin-details/gathering/gathering.html
This looked like it had already been done, but it needed a little love.
The first thing I did was to make sure HTML would be rendered appropriately. In many cases this will push the "Read More" button down, so I put it on the next line below the description. And I made it read "Read More" because "More" felt like it wasn't super intuitive given that it's detached from the content above it.
> DE4117 - Edit Group Button

- src/app/components/filters/filters.component.ts
- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.scss
- src/app/services/state.service.ts
Current behavior:
When filters are applied, equalizer icon does not change color to reflect the enabled state.
Expected behavior:
When returned to map/list page, the equalizer icon in the search bar should display an enabled state. Use $cr-teal for this. 
---
crdschurch/crds-styles#201
> DE4077 - Active Filter Button

- src/app/components/search-bar/search-bar.component.spec.ts
- src/app/components/search-bar/search-bar.component.ts
https://rally1.rallydev.com/#/66097202244d/detail/defect/146571902544
> Single quotes in search string are now URL encoded to %27

- .editorconfig
- README.md
- package.json
- tslint.json
[Editor Config](http://editorconfig.org/)
This will add rules and enforce the spacing for our typescript / js files in the connect repository. This works out of the box for some editors (IntelliJ). Other editors require the user to install a plugin for the enforcement to occur. 
- [VSCode](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
- [Atom](https://github.com/sindresorhus/atom-editorconfig#readme)
- [Emacs](https://github.com/editorconfig/editorconfig-emacs#readme)
This change will require an npm i
> add editorconfig and 2 spaces to tslint

- src/app/components/create-group/page-6/create-group-page-6.component.html
Two of the field validation errors for page 6 are not accessible by the usual means we use to validate field errors and needed a more unique way of being located.
> Added data-automation-ids to less accessible error messages

- src/app/components/bland-page/bland-page.component.ts
Hide the double scrollbar on bland pages.
Recreate by clicking "Contact Leader" on any group and submitting the form. The confirmation fauxdal is what was effected.
> DE4290 - Double scroll

- src/app/components/pin-details/gathering/gathering.html
- src/styles/pages/_pin-details.scss
Rework the pin detail markup so the edit group button is on a new line and the read more link is more inline with the shortened description.
No corresponding PRs. The "end group" button was commented out by Analog. I styled it and recommented it out because YOLO
> DE4286 - Pin details layout

- src/app/components/pin-details/gathering/participant-card/participant-card.html
Refactor markup to make entire participant card clickable. Won't be clickable on "me" labeled participants.
No associated PRs
> DE4219 - Card click area

- src/app/components/search-bar/search-bar.component.html
Remove divider line on connect.
---
go to /connect
The horizontal rule we put in place between keyword & location search on /groups is showing on the far right on /connect. It should not display on connect at all. 
> DE4420 - Searchbar divider

- src/app/components/search-bar/search-bar.component.ts
Ensure that the 'x' shows up when viewing 'My Groups'
> DE4443 My Groups

- src/app/components/search-bar/search-bar.component.html
- src/app/components/search-bar/search-bar.component.spec.ts
- src/app/components/search-bar/search-bar.component.ts
- src/styles/components/_searchbar.scss
Fix interaction on searchbar/filter tray. 
Filter icon should open filter tray and location input. 
Clicking cancel should close filter tray and location input. 
Clicking into the keyword input should open the location input without opening the filter tray.
Should test /connect and /groups since this component's shared in both.
> DE4487 - Filter icon tray
